### PR TITLE
Created elementary parser, add your thoughts

### PR DESCRIPTION
**Pull request by JerryTeng01**

### CODE REVIEW

**Comment by ez314** [comment]
awesome work on getting all the modules working together!

**Comment by ez314** [comment]
Note on the readability scores and grammar checks: the parser is sometimes not adding spaces where there need to be spaces, and this leads to words being joined together. I think this is interpreted as "bad grammar" and being "difficult to read"

**Comment by ez314** [comment]
If someone would like to make the latest commit more readable, feel free to do that.

**Comment by adityarathod** [comment]
> If someone would like to make the latest commit more readable

no❤️

just kidding—this is some very cool stuff

**Comment by ez314** [comment]
@adityarathod I was just about to ask if someone wanted to move hard-coded stuff to CLI arguments, thanks for volunteering!

**Pull request merged**
